const path=require('path')
const express=require('express')
const dotenv=require('dotenv')
const morgan=require('morgan')
const exphbs=require('express-handlebars')
const passport=require('passport')
const session=require('express-session')
const connectDB=require('./config/db')